name: Deploy Ziggurat visualizer

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "!.github/**"

jobs:
  deploy-ziggurat-visualier:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: europe-west3-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - id: build-docker-image
      name: Build Docker image using BuildKit
      uses: docker/build-push-action@v2.10.0
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: europe-west3-docker.pkg.dev/eqg-ziggurat/eqg-ziggurat/eqg-ziggurat-visualizer:${{github.ref_name}}
          
    - name: Run Ziggurat visualizer
      run: |
        gcloud compute ssh eqg-ziggurat-visualizer --zone=europe-west1-b -- docker rm -f $(docker ps -aq) && sudo docker pull europe-west3-docker.pkg.dev/eqg-ziggurat/eqg-ziggurat/eqg-ziggurat-visualizer:${{github.ref_name}} && sudo docker run europe-west3-docker.pkg.dev/eqg-ziggurat/eqg-ziggurat/eqg-ziggurat-visualizer:${{github.ref_name}} -p 3000:3000
