name: Deploy Ziggurat visualizer

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "!.github/**"

jobs:
  deploy-ziggurat-visualier:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Upload Ziggurat to Cloud Storage
      run: |
        gsutil -m cp -r ../showme gs://eqg-ziggurat-bucket/

    - name: Update GCE instance metadata with changes
      run: |
        gcloud compute ssh eqg-ziggurat-visualizer --zone=europe-west1-b -- rm -rf shomwe && gsutil -m cp -r gs://eqg-ziggurat-bucket/showme .
  
    - name: Stop previous Ziggurat visualizer
      run: |
        gcloud compute ssh eqg-ziggurat-visualizer --zone=europe-west1-b -- sudo npm install pm2 -g
        gcloud compute ssh eqg-ziggurat-visualizer --zone=europe-west1-b -- ls && cd showme && npm i && npm run build && pm2 delete 0 && pm2 start "npm run start" --name egq-visualizerr
